version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pbl7_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      # Ánh xạ cổng (Máy tính của bạn : Bên trong Docker)
      - "5433:5432"
    volumes:
      # Tự động nạp file init.sql vào database ở lần khởi động đầu tiên
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # Lưu dữ liệu vĩnh viễn
      - pbl7_pgdata:/var/lib/postgresql/data

volumes:
  pbl7_pgdata: