version: '3.8'

services:
  # ==========================================
  # 1. DATABASE (POSTGRESQL)
  # ==========================================
  db:
    image: postgres:15-alpine
    container_name: pbl7_database_v2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5434:5432" # Ánh xạ cổng ra ngoài cho host
    volumes:
      - ./postgres_docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pbl7_pgdata:/var/lib/postgresql/data

  # ==========================================
  # 2. APACHE SPARK (MASTER)
  # ==========================================
  spark-master:
    build: 
      context: ./Spark
    container_name: pbl7-spark-master
    hostname: pbl7-spark-master
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - pbl7-spark-master
      - --port
      - "7077"
      - --webui-port
      - "8080"
    ports:
      - "8082:8080"
      - "7078:7077"
    volumes:
      - ./Spark/app:/app
    depends_on:
      - db

  # ==========================================
  # 3. APACHE SPARK (WORKER)
  # ==========================================
  spark-worker:
    build: 
      context: ./Spark
    container_name: pbl7-spark-worker
    hostname: pbl7-spark-worker
    depends_on:
      - spark-master
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://pbl7-spark-master:7077
      - --cores
      - "2"
      - --memory
      - 2G
      - --webui-port
      - "8081"
    ports:
      - "8083:8081"
    volumes:
      - ./Spark/app:/app

  # ==========================================
  # 4. WEB APP (DJANGO API)
  # ==========================================
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pbl7_django
    working_dir: /app/pbl7_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=postgres

  # ==========================================
  # 5. SCHEDULER (AUTO PIPELINE BACKGROUND WORKER)
  # ==========================================
  scheduler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pbl7_scheduler
    working_dir: /app/pbl7_web
    command: python manage.py auto_pipeline
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=postgres

volumes:
  pbl7_pgdata: