# Generated by Django 6.0.5 on 2026-05-27 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleKeywordMap',
            fields=[
                ('article_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
            ],
            options={
                'db_table': 'article_keyword_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordDailyStats',
            fields=[
                ('date', models.TextField(db_column='Date', primary_key=True, serialize=False)),
                ('keyword', models.TextField(db_column='Keyword')),
                ('count', models.BigIntegerField(blank=True, db_column='Count', null=True)),
            ],
            options={
                'db_table': 'keyword_daily_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('clean_title', models.TextField(blank=True, null=True)),
                ('clean_content', models.TextField(blank=True, null=True)),
                ('full_clean_text', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendingKeywords',
            fields=[
                ('keyword', models.TextField(db_column='Keyword', primary_key=True, serialize=False)),
                ('popularity', models.FloatField(blank=True, db_column='Popularity', null=True)),
                ('trend', models.FloatField(blank=True, db_column='Trend', null=True)),
                ('z_score', models.FloatField(blank=True, db_column='Z_Score', null=True)),
                ('specific_weight', models.FloatField(blank=True, db_column='Specific_Weight', null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('pop_norm', models.FloatField(blank=True, db_column='Pop_Norm', null=True)),
                ('trend_norm', models.FloatField(blank=True, db_column='Trend_Norm', null=True)),
                ('z_score_norm', models.FloatField(blank=True, db_column='Z_Score_Norm', null=True)),
                ('super_hot_score', models.FloatField(blank=True, db_column='SUPER_HOT_SCORE', null=True)),
            ],
            options={
                'db_table': 'trending_keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LdaTopic',
            fields=[
                ('topic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255)),
                ('acceleration', models.FloatField(default=0.0)),
                ('trend_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lda_topics',
            },
        ),
        migrations.CreateModel(
            name='ArticleTopicMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.BigIntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ldatopic')),
            ],
            options={
                'db_table': 'article_topic_map',
            },
        ),
        migrations.CreateModel(
            name='TopicDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('article_count', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ldatopic')),
            ],
            options={
                'db_table': 'topic_daily_stats',
                'unique_together': {('date', 'topic')},
            },
        ),
    ]
